/* Deliverable 3
*  Team 18
*  Jonah Cole, Ryan Cluff, Dylan Sund
*/

CREATE TABLE CUSTOMER(
Email VARCHAR(50) NOT NULL,
Name VARCHAR(15) NOT NULL,
Address VARCHAR(30),
PhoneNumber VARCHAR(11),
PRIMARY KEY(Email));

CREATE TABLE EMPLOYEE(
SSN CHAR(9) NOT NULL,
Name VARCHAR(15) NOT NULL,
Address VARCHAR(30),
PhoneNumber VARCHAR(11),
PRIMARY KEY(SSN));

CREATE TABLE CUSTOMER_ORDER(
OrderId VARCHAR(25) NOT NULL,
CEmail VARCHAR(50),
DatePlaced Date NOT NULL,
FOREIGN KEY(CEmail) REFERENCES CUSTOMER(Email),
PRIMARY KEY(OrderId));

CREATE TABLE PRODUCT(
ProductId VARCHAR(30) NOT NULL,
Name VARCHAR(15),
Price VARCHAR(10),
Description VARCHAR(60),
PRIMARY KEY(ProductId));

CREATE TABLE LOCATION(
LocationId VARCHAR(20) NOT NULL,
Address VARCHAR(30),
PhoneNumber VARCHAR(11),
PRIMARY KEY(LocationId));

CREATE TABLE ORDER_CONTAINS(
OrderId VARCHAR(25) NOT NULL,
ProductId VARCHAR(30) NOT NULL,
ItemCount INT,
FOREIGN KEY(OrderId) REFERENCES CUSTOMER_ORDER(OrderId),
FOREIGN KEY(ProductId) REFERENCES PRODUCT(ProductId),
PRIMARY KEY(OrderId, ProductId));

CREATE TABLE FULFILLED_BY(
OrderId VARCHAR(25) NOT NULL,
eSSN CHAR(9) NOT NULL,
FOREIGN KEY(OrderId) REFERENCES CUSTOMER_ORDER(OrderId),
FOREIGN KEY(eSSN) REFERENCES EMPLOYEE(SSN),
PRIMARY KEY(OrderId, eSSN));

CREATE TABLE WORKS_AT(
LocationId VARCHAR(20) NOT NULL,
eSSN CHAR(9) NOT NULL,
FOREIGN KEY(LocationId) REFERENCES LOCATION(LocationId),
FOREIGN KEY(eSSN) REFERENCES EMPLOYEE(SSN),
PRIMARY KEY(LocationId, eSSN));

CREATE TABLE STORED_AT(
LocationId VARCHAR(20) NOT NULL,
ProductId VARCHAR(30) NOT NULL,
ItemCount INT,
FOREIGN KEY(LocationId) REFERENCES LOCATION(LocationId),
FOREIGN KEY(ProductId) REFERENCES PRODUCT(ProductId),
PRIMARY KEY(LocationId, ProductId));